### ISSUE TITLE
not able to supply wildfly as off-line file

### ISSUE THREAD

**Issue by ltutar** [coi-gov-pl/puppet-jboss#17]
I have the following yaml:
boss::params::product: 'wildfly'
jboss::params::version: '8.2.11.Final'
jboss::params::download_url: '/vagrant/salt/states/puppetmaster/files/wildfly-external-resources/wildfly-8.2.1.Final.zip'

using /vagrant or file:/vagrant will not help. It would be nice to supply the wildfly offline.

Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns: [/usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip]
Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns:   End-of-central-directory signature not found.  Either this file is not
Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns:   latter case the central directory and zipfile comment will be found on
Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns:   the last disk(s) of this archive.
Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns: unzip:  cannot find zipfile directory in one of /usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip or
Notice: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns:         /usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip.zip, and cannot find /usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip.ZIP, period.
Error: unzip -o -q /usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip -d /usr/lib/wildfly-8.2.11.Final returned 9 instead of one of [0]
Error: /Stage[main]/Jboss::Internal::Package/Exec[jboss::unzip-downloaded]/returns: change from notrun to 0 failed: unzip -o -q /usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip -d /usr/lib/wildfly-8.2.11.Final returned 9 instead of one of [0]

**Comment by therek** [comment]
Have you tried to specify it as file:///vagrant/(...) - three slashes?

**Comment by ltutar** [comment]
Yes. It will not work. It switches then to http.

Error: wget -q 'http://download.jboss.org/wildfly/8.2.11.Final/wildfly-8.2.11.Final.zip' -O '/usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip' && chmod 0640 '/usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip' && chown jboss:jboss '/usr/src/download-wildfly-8.2.11.Final/wildfly-8.2.11.Final.zip' returned 8 instead of one of [0]

**Comment by ltutar** [comment]
I had to define in yaml
jboss::params::download_urlbase: '/vagrant/salt/states/puppetmaster/files/wildfly-external-resources'

since in init.pp the following makes up the parameter.
  $download_url     = "${jboss::params::download_urlbase}/${product}/${version}/${product}-${version}.zip",

**Comment by therek** [comment]
I reopen it. There's clearly a missmatch between `download_url` and `download_urlbase` parameters and I think it should be addressed.

**Comment by therek** [comment]
Fixed. Will be available in v1.0.3.

**Comment by cardil** [comment]
Release v1.0.3 has been released into central puppet forge repository. Here are release notes: https://github.com/coi-gov-pl/puppet-jboss/releases/tag/v1.0.3

Thanks for your contribution! :smile:

**Comment by ltutar** [comment]
Thank you. The following yaml works:
```
jboss::params::download_url: 'puppet:///puppet_files/wildfly/wildfly-8.2.1.Final.zip'
#jboss::params::download_urlbase: 'puppet:///puppet_files/wildfly'
```
