### ISSUE TITLE
java_autoinstall parameter is implemented as java_install in params.pp

### ISSUE THREAD

**Issue by ltutar** [coi-gov-pl/puppet-jboss#21]
According to README.md
```
By default module will install default Java JDK using puppetlabs/java module. This can be turned off by using $jboss::java_autoinstall variable or hiera key: jboss::params::java_autoinstall
```
But in params.pp, the key is not java_autoinstall but java_install
```
$java_autoinstall = jboss_to_bool(hiera('jboss::params::java_install', true))
```

**Comment by cardil** [comment]
Fix for this issue has been released into central puppet forge as release v1.0.3. Here are release notes: https://github.com/coi-gov-pl/puppet-jboss/releases/tag/v1.0.3

Thanks for your contribution!
