### ISSUE TITLE
Support for add-protocol() and remove-protocol() in lib/provider/jboss_confignode

### ISSUE THREAD

**Issue by naefhe** [coi-gov-pl/puppet-jboss#38]
Hi,

We are heavily working with the COI puppet-jboss module and currently develop an extension to manage domain profiles. Currently, we plan to generate profiles based on the "ha" profile suppled by JBoss EAP 6.4. The module extension is almost complete. The "JBoss not running" part is complete and tested, however, right now, we stuck with the "JBoss running" part attempting to implement the jgroups subsystem. In order to manage the jgroups udp and tcp protocols, the JBoss CLI functions add-protocol() and remove-protocol() functions are used, but they are not (yet) implemented in the provider library function jboss_confignode.

Do you see a reasonable way to implement add-protocol() and remove-protocol() in jboss_confignode?

Thanks, and cheers,
 Heinz

**Comment by cardil** [comment]
Seems quite reasonable. We need to think of the best way to do this.

**Comment by cardil** [comment]
@naefhe Could you supply us with exact CLI command's and JBoss output to them. That would help a lot!

**Comment by naefhe** [comment]
Hi cardil,

These are the two complementary operations at the JBoss CLI directly:

[domain@localhost:9999 /] /profile=ha-p2p-tst4-ext/subsystem=jgroups/stack=udp:add-protocol(type=PING)
{
    "outcome" => "success",
    "result" => undefined,
    "server-groups" => undefined
}
[domain@localhost:9999 /] /profile=ha-p2p-tst4-ext/subsystem=jgroups/stack=udp:remove-protocol(type=PING)
{
    "outcome" => "success",
    "result" => undefined,
    "server-groups" => undefined
}
[domain@localhost:9999 /]

I don't see a way to specify this in jboss::clientry. Looking into lib/Provider/jboss_confignode, it is not implemented (e. g. in the create section).

Cheers,
 Heinz

**Comment by cardil** [comment]
Thanks for those commands. That's exactly what we need. I think we will talk about it tomorrow with @therek and @Cosaquee and will give you feedback as soon as possible.

Stay tuned.

**Comment by cardil** [comment]
I've looked it up. And it seams to be exactly as you written. I've also been looking for other solution:

```puppet
class { 'jboss':
  product      => 'jboss-eap',
  version      => '6.4.0.GA',
  download_url => 'http://public.internal/jboss/jboss-eap-6.4.0.GA.zip',
  runasdomain  => true,
}

jboss::clientry { '/subsystem=jgroups/stack=udp/protocol=PING':
  ensure  => 'absent',
  profile => 'ha',
}
```

And unfortunately fails with error:

```
Error: /Stage[main]/Main/Jboss::Clientry[/subsystem=jgroups/stack=udp/protocol=PING]/Jboss_confignode[/subsystem=jgroups/stack=udp/protocol=PING]/ensure: change from present to absent failed: 
Configuration node failed to remove:
[CLI command]: /profile=ha/subsystem=jgroups/stack=udp/protocol=PING:remove()
[Error message]: {
    "outcome" => "failed",
    "failure-description" => "JBAS014884: No operation named 'remove' exists at address [
    (\"profile\" => \"ha\"),
    (\"subsystem\" => \"jgroups\"),
    (\"stack\" => \"udp\"),
    (\"protocol\" => \"PING\")
]",
    "rolled-back" => true
}
``` 

This all is that there is no standard methods: `add` and `remove` for CLI path `/profile=yyyyyy/subsystem=jgroups/stack=udp/protocol=XXXX`. You actually need use methods `add-protocol` and `remove-protocol` to path `/profile=yyyyyy/subsystem=jgroups/stack=udp` :-1:  :-1: 

**There is not workaround for now. There needs to be some work done to make it work** :-/

I was wondering about how to do this. I fought o 2 possible solutions:

#### 1. Modify the `jboss::clientry` to add hooks

```puppet
jboss::clientry { '/subsystem=jgroups/stack=udp':
  ensure => 'present'
  hooks  => {
    # posible other hooks like: pre-present, post-absent-pre-absent
    'post-present' => {
      'exec'   => ':add-protocol(type=PING)',
      'unless' => '/protocol=PING:read-resource',
    },
  },
}
```

#### 2. Add define `jboss::exec` similar to puppet `exec` resource

```puppet
jboss::exec { '/subsystem=jgroups/stack=udp:add-protocol(type=PING)':
  unless     => '/subsystem=jgroups/stack=udp/protocol=PING:read-resource',
  # also onlyif, and maybe refreshonly?!?
}
```

What do you think? @naefhe @coi-gov-pl/jboss-puppet-team ? Maybe some other idea for implementation.

**Comment by Cosaquee** [comment]
I opt for solution 2. More readable imho.

**Comment by therek** [comment]
+1 for second solution as well.

**Comment by cardil** [comment]
I'm also opting for second solution. I will create a ticket to describe it in more detail and I will link it here.

**Comment by cardil** [comment]
Feature request specification has been specified in #42. Feel free to comment there @naefhe.
