### ISSUE TITLE
Improper handling of download_url parameter

### ISSUE THREAD

**Issue by cardil** [coi-gov-pl/puppet-jboss#65]
`download_url` parameter in main class `jboss` has been moved to params file in commit https://github.com/coi-gov-pl/puppet-jboss/commit/26c7345022ab95b619c95cfabdb3720acce6b672 (PR #26). This causes numerous issues when overriding `$product` or `$version` parameters using main class. Like this:

```puppet
class { 'jboss':
  product => 'wildfly',
  version => '9.0.2.Final',
}
```

In this example `$download_url` is being resolved in `params.pp` file and default values of `$product` and `$version` are being used.

There are 2 propositions to fix this:

#### Move download_url to runtime class and calculate there

* Moving `$download_url` to `jboss::internal::runtime` class
* Set parameters from `jboss` class to `jboss::internal::runtime` class
* Use parameters from `jboss::internal::runtime` class instead of `params.pp`
* Update all references to `$jboss::internal::runtime::download_url` instead of `$jboss::params::download_url`

#### Calculate in params using product and version in runtime class

* Set parameters from `jboss` class to `jboss::internal::runtime` class
* Use parameters from `jboss::internal::runtime` class instead of `params.pp`

**Comment by Cosaquee** [comment]
I think that first option is better so i will do that.
