### ISSUE TITLE
Support for rake v11.0

### ISSUE THREAD

**Issue by Cosaquee** [coi-gov-pl/puppet-jboss#74]
In the newest version of Rake there is no support for Ruby version 1.8. We need to still support  it so we need to download rake 10.5 in Gemfile for 1.8. In versions >1.8 we will use newest version of Rake.

**Comment by cardil** [comment]
RSpec has been released 35min ago: https://github.com/rspec/rspec-core/compare/v3.4.3...v3.4.4
