### ISSUE TITLE
Add support to puppetlabs/concat > 2.x

### ISSUE THREAD

**Issue by LaurentChardin** [coi-gov-pl/puppet-jboss#85]
Hello,

I didn't test yet but would this module be compatible with concat 2.1.0 ?

I have another module which installed concat 2.1.0, resulting in puppet-jboss failing the dependency check (and puppet tried to download puppet-jboss 1.0.2 instead).

puppet-jboss 1.0.3:
`{ "name": "puppetlabs/concat", "version_requirement": ">= 1.0.0 <2.0.0" }`

puppet-jboss 1.0.2:
`{"name":"puppetlabs/concat","version_requirement":">= 1.0.0"}`

**Comment by cardil** [comment]
Thank you for your input!

I've checked `puppetlabs/concat` and version `2.x` isn't compatible with Puppet 2.x and Ruby 1.8 we are supporting in this module right now. We are planning to drop support for old version of Ruby and Puppet in near future. It is planned with 2.0.0 release of this module.

We will double check if our module can work well with newer versions of concat module, despite the clear specified requirements of it:

```
"requirements": [
    {
      "name": "pe",
      "version_requirement": ">= 3.7.0 < 2015.4.0"
    },
    {
      "name": "puppet",
      "version_requirement": ">= 3.0.0 < 5.0.0"
    }
  ]
```

When we will check that we will post here what we came up to. Thanks again!
