### ISSUE TITLE
Puppet approved

### ISSUE THREAD

**Issue by tphoney** [coi-gov-pl/puppet-jboss#92]
Hi !

we heard a lot of good things about this module, and reviewed it as part of making it an approved module on the puppet forge: https://forge.puppet.com/approved

We did have one question about the module, have you verified using the module with puppet 4 or are you looking at supporting it going forward ? 

The module is great, keep up the good work.

Cheers,
TP

**Comment by cardil** [comment]
Yes, it is planned for 2.0 release. See here: https://github.com/coi-gov-pl/puppet-jboss/milestone/3

**Comment by tphoney** [comment]
This is great news, apologies for the slow response. Great work !!!
