### ISSUE TITLE
Intermittent error while resolving custom fact "jboss_running"

### ISSUE THREAD

**Issue by naefhe** [coi-gov-pl/puppet-jboss#97]
In our logs, we intermittently see the following error message:

**Error: Facter: error while resolving custom fact "jboss_running": No such file or directory @ rb_sysopen - /proc/_[1-9][0-9]*_/cmdline**

We could imagine a race condition between the custom fact thread and (RHEL 7) OS threads that cause proc filesystem directory elements to change or even disappear before they are 'read' in the Dir block.

Impacts:
- Undesired JBoss (domain controller or slave server) restarts

Suggested solution:
1. In the Dir block, check if **file** exists before attempting to read
2. Restrict the search to the JBoss Host Controller JVM, org.jboss.as.host-controller 

File: puppet-jboss/lib/facter/jboss_running.rb

Do you agree with our Interpretation and suggestions?

Cheers,

**Comment by naefhe** [comment]
We had some occurrences of this issue. Did it happen in anyone else's environments?
Is anyone working on this issue?
Cheers,
 Heinz

**Comment by cardil** [comment]
Hello,

I'm currently working on stabilizing tests #101 to enable `coi/jboss` to move further. And I've also came up to the same error.

I've fixed it already in my branch, here: https://github.com/coi-gov-pl/puppet-jboss/blob/bugfix/stabilizing-tests/lib/puppet_x/coi/jboss/facts.rb#L123-L128

I'm finishing my PR so hopefully it will be merged soon, and realesed after :-)

**Comment by cardil** [comment]
PR #101 has been merged. Is there a change you can test your code vs latest develop branch of `coi/jboss` to test if your error has been fixed?!
